Очки термального зрения
Space-Stories/space-station-14 pull request #138
Opened 2024-10-20 00:18 UTC by pheenty

## О PR

Очки термального зрения. Весьма самообъясняюще. Скорее всего, будут в аплинке у агентов и оперов.
## Почему / Баланс

Это было в сс13
## Технические детали

Есть ThermalVisionComponent, а есть NightvisionComponent с NightvisionClothingComponent. Теперь есть ThermalVisionClothingComponent.
## Медиа

- [ ] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**

<!--
Убедитесь, что вы убрали этот шаблон Changelog из блока комментариев, чтобы он отображался.
:cl:
- add: Очки термального зрения

2024-10-25 11:38 UTC, pheenty commented
@doublechest0 ну как там?

2024-11-01 16:56 UTC, doublechest0 requested changes

2024-11-01 16:56 UTC, doublechest0 commented on Resources/Textures/Stories/Clothing/Eyes/Glasses/termalhud.rsi/action.png
Нужно убрать, так как это текстура другого назначения.

2024-11-01 16:56 UTC, doublechest0 commented on Resources/Textures/Stories/Clothing/Eyes/Glasses/termalhud.rsi/meta.json
> +  "license": "Собственная лицензия. Копирование, модификация и использование вне проекта Space Stories полностью запрещено без предварительного согласия текущего владельца проекта",
Проверки не пропускают это.

2024-11-01 16:56 UTC, doublechest0 commented on Resources/Textures/Stories/Clothing/Eyes/Glasses/termalhud_oneglass.rsi/meta.json
> +  "license": "Собственная лицензия. Копирование, модификация и использование вне проекта Space Stories полностью запрещено без предварительного согласия текущего владельца проекта",
Проверки не пропускают это.

2024-11-01 18:01 UTC, pheenty commented
А, понял чё за приколы с проверками, думал ему просто русские буквы не нравятся

2024-11-01 20:07 UTC, doublechest0 commented on Content.Server/Stories/ThermalVision/ThermalVisionSystem.cs
> +    if (args.Slot == "eyes" && !HasComp<ShadowlingThrallComponent>(args.Equipee))
Сомнительная хардкод проверка

2024-11-01 20:08 UTC, pheenty commented on Content.Server/Stories/ThermalVision/ThermalVisionSystem.cs
> +    if (args.Slot == "eyes" && !HasComp<ShadowlingThrallComponent>(args.Equipee))
> Сомнительная хардкод проверка

Окей, добавлю bool isInnate

2024-11-02 15:52 UTC, doublechest0 approved these changes

2024-11-02 15:52 UTC, merged