Night vision toggling
Space-Stories/space-station-14 pull request #151
Opened 2024-10-21 14:08 UTC by pheenty

## О PR

Добавляет возможность переключения прибора ночного видения и очков ниндзя.
## Почему / Баланс

Частично фиксит https://github.com/Space-Stories/space-station-14/issues/49.
Тенеморфу добавлю аналогичное в https://github.com/Space-Stories/space-station-14/pull/138
Нужно, чтобы дать ночное зрение дракону и карпам по итогам https://discord.com/channels/1111698541841240164/1297618376998387912

## Медиа

![image](https://github.com/user-attachments/assets/bacabb4e-5613-4afb-acd0-dded955b3bed)
![image](https://github.com/user-attachments/assets/499b96aa-8d4a-467d-8336-fa518a2f8854)

- [X] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**

:cl: pheenty
- add: Прибор ночного видения теперь можно переключать.

2024-10-22 20:11 UTC, doublechest0 requested changes

2024-10-22 20:46 UTC, pheenty commented on Content.Shared/Stories/Nightvision/NightvisionComponent.cs
> +    public SoundSpecifier ToggleOnSound = new SoundPathSpecifier("/Audio/Stories/Misc/night_vision.ogg");
Вот так?

2024-10-25 18:28 UTC, doublechest0 approved these changes

2024-10-25 18:29 UTC, doublechest0 requested changes
Переработай всю систему на использование ItemToggle

2024-10-25 19:01 UTC, pheenty commented
> Переработай всю систему на использование ItemToggle

А для дракона тогда как?

2024-11-01 16:59 UTC, merged