Бронежилет инквизитора
Space-Stories/space-station-14 pull request #243
Opened 2024-11-07 02:26 UTC by SHEGARE

## О PR

Closes #207

## Технические детали

Перенёс часть резистов в бронежилет, часть оставил в плаще

## Медиа

![Content Client_DfaEhZCCpr](https://github.com/user-attachments/assets/7f67d583-003b-4d9c-a7a0-4092a34ba0f6)
![Content Client_vebd2senRn](https://github.com/user-attachments/assets/bb5116ec-d8ae-4d20-b70f-0cb9e683c7ff)
- [X] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**

:cl: Shegare
- add: Инквизитору добавлен бронежилет

2024-11-07 05:36 UTC, pheenty commented
А кайло Рену тоже самое?

2024-11-07 11:13 UTC, SHEGARE commented
> А Кайло Рену то же самое? Да и я бы ВСЕ резисты в броник перенёс, кроме как защиты от разгермы и низких температур

Вроде и так тир 1 бронежилет (либо близко к этому). Также я оставил тот урон что никак в моём понимании не должен защищать в бронежилете, к примеру радиация, плащ накрывает и допустим блочит раду, а как это бронежилет должен делать?

Если хочешь можешь сам потом до перенести, я главное сделал спрайт броника, сделал прототип, а остальное на броник переносить неприятно

2024-11-07 11:59 UTC, doublechest0 requested changes

2024-11-07 11:59 UTC, doublechest0 commented on Resources/Prototypes/Stories/Entities/Clothing/Neck/cloaks.yml
> +  description: Плащ оформленный как невероятное произведение искусства. Заряжен неведомой энергией.
Не описывает его.

2024-11-07 11:59 UTC, doublechest0 commented on Resources/Prototypes/Stories/Entities/Clothing/OuterClothing/vests.yml
> +  description: Грозный бронежилет, перенесёт даже ядерный взрыв.
Глупое описание.

2024-11-07 13:20 UTC, SHEGARE commented
Теперь менее кринжовые описания?

2024-11-07 16:09 UTC, doublechest0 commented
Возможно, стоит добавить и кайло рену, если нам нем кто-то играет.

2024-11-07 16:43 UTC, SHEGARE commented
> Возможно, стоит добавить и кайло рену, если нам нем кто-то играет.

![image](https://github.com/user-attachments/assets/863fade9-4623-4e75-bc25-99ddc63570e0)
Только сейчас узнал что есть альт экип

2024-11-07 17:27 UTC, SHEGARE commented
Ну вот теперь точно всё...

2024-11-08 18:12 UTC, doublechest0 approved these changes

2024-11-08 18:12 UTC, merged