Clothingwhitelisttweaks
Space-Stories/space-station-14 pull request #256
Opened 2024-11-07 13:11 UTC by pheenty

## О PR

1) скафандры яо не взрываются на существах без dnacomponent, например на манекенах.
2) рейдерский костюм теперь тоже взрывается.
3) скафандры ОБР больше нельзя емагнуть, ничего не сделав и просто потратив заряд. формально они просто емагнуты изначально. хотя я почти уверен, что никто и не знал, что по ним можно нажать емагом.
4) вместо прописывания взрыва в каждом скафандре яо теперь есть BaseSyndicateExplodingClothing. вместо прописывания null вайтлиста в скафандрах ОБР теперь есть BaseERTNotExplodingClothing
5) using в ClothingWhitelistSystem отсортированы по алфавиту, удалены лишние
6) удалён функционал вайтлиста компонентов
## Почему / Баланс

1) по просьбам мапперов, по факту фикс
2) по факту фикс
3) фикс, хоть и костыльный
4) упрощение кода
5) да
6) он бесполезен
## Технические детали

нет
## Медиа

- [X] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**

:cl: pheenty
- add: Рейдерский костюм Синдиката теперь тоже имеет биокод.
- fix: Скафандры ЯО больше не взрываются на манекенах.

2024-11-08 06:45 UTC, pheenty commented
Под каким веществом я вчера это делал, вырезав проверки на компоненты из системы, но оставив вайт/блеклист компонентов в самом компоненте... Приду домой - починю

2024-11-08 18:16 UTC, doublechest0 requested changes

2024-11-08 18:16 UTC, doublechest0 commented on Content.Server/Stories/ClothingWhitelist/ClothingWhitelistSystem.cs
> +        else return;
```
if (!TryComp<NpcFactionMemberComponent>(args.Equipee, out var npc))
   return;
```

2024-11-12 11:00 UTC, doublechest0 approved these changes

2024-11-12 11:00 UTC, merged