Add: humans can have horns now
Space-Stories/space-station-14 pull request #276
Opened 2024-11-17 07:37 UTC by NoElkaTheGod

## О PR
Людям в меню кастомизации персонажа теперь доступно два типа рожек. 

## Почему / Баланс
1. Предложение в дискорде (https://discord.com/channels/1111698541841240164/1307264183313891328) с приличным количеством звёздочек.
2. У нас уже есть кошачьи ушки, так что почему нет?
3. Это даже не фурри, поэтому никто не будет жаловаться. Наверное.
4. Они выглядят мило.
5. Больше разнообразия это хорошо.
6. Вообще не влияет на баланс, это косметика.

## Технические детали
Спрайты позаимствованы у унатхов и немного модифицированы. В остальном исключительно мелкие изменения в прототипах (ну и локализация, конечно же).

## Медиа
![horns 2 0](https://github.com/user-attachments/assets/cb22e124-94a7-4326-babf-e7b7a704c349)

- [X] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**
:cl:
- add: Добавлены рожки в меню кастомизации.

2024-11-17 08:14 UTC, NoElkaTheGod commented
Тест нагло врёт, всё нормально работает

2024-11-17 10:22 UTC, Onepersic commented
Всем своим сердцем за

2024-11-17 10:54 UTC, pheenty commented
Сначала ушки, теперь рожки... Что дальше? ЕРП панель?

2024-11-17 11:05 UTC, Onepersic commented
ЕРП панель на следующий год :)))

2024-11-17 11:06 UTC, SHEGARE commented
> Сначала ушки, теперь рожки... Что дальше? ЕРП панель?

ЕРП панель Метал накодит

2024-11-17 12:05 UTC, NoElkaTheGod commented
> Сначала ушки, теперь рожки... Что дальше? ЕРП панель?

Да ЕРП сервер бы сначала открыли, какая там панель. 

И вообще, как рожки связаны с ЕРП? Я конечно не осуждаю, но у тебя странные фетиши :jokerge:

2024-11-17 12:06 UTC, NoElkaTheGod commented
~~А ещё ЕРП панель только вредит процессу~~

2024-11-17 20:26 UTC, doublechest0 requested changes

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Textures/Mobs/Customization/horns.rsi/meta.json
В Stories/

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Textures/Mobs/Customization/horns.rsi/horns_simple.png
В Stories/

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Textures/Mobs/Customization/horns.rsi/horns_short.png
В Stories/

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Prototypes/Species/slime.yml
> +    HeadTop: MobSlimeMarkingFollowSkin
```suggestion
    HeadTop: MobSlimeMarkingFollowSkin # Stories
```

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Prototypes/Species/slime.yml
> +      required: false
```suggestion
    HeadTop: # Stories - start
      points: 1
      required: false # Stories - end
```

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/horns.yml
В Stories/

2024-11-17 20:26 UTC, doublechest0 commented on Resources/Locale/ru-RU/markings/horns.ftl
В Stories/

2024-11-18 07:06 UTC, NoElkaTheGod commented
Внёс запрошенные изменения, и даже ничего не сломал.

2024-11-21 10:53 UTC, doublechest0 approved these changes

2024-11-21 10:53 UTC, merged