Удавка завершённая
Space-Stories/space-station-14 pull request #292
Opened 2024-11-25 21:20 UTC by Shegare

## О PR

Closes https://github.com/Space-Stories/space-station-14/issues/259

Продолжение https://github.com/Space-Stories/space-station-14/pull/275
## Технические детали

* Добавлены спрайты.
* Для использования проверяет, совпадает ли направление взгляда пользователя с направлением взгляда цели.
* Используется вплотную.
## Медиа

![Aseprite_jq7cgF5wQs](https://github.com/user-attachments/assets/3bb6ad58-903f-49db-bc1d-99a65e14161f)
- [X] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**

:cl: pheenty и Shegare
- add: В аплинк добавлена удавка, позволяющая агентам Синдиката и Ядерным Оперативникам тихо устранять одиночные цели.

2024-11-25 21:28 UTC, Shegare commented
Втф, чё не так?

2024-11-25 21:37 UTC, Shegare commented
Не могу написать в коммите png...

2024-11-26 18:21 UTC, doublechest0 requested changes

2024-11-26 18:21 UTC, doublechest0 commented on Content.Server/Stories/Garrote/GarroteSystem.cs
> +        DamageSpecifier damage = new(_prototypeManager.Index<DamageTypePrototype>("Asphyxiation"), comp.Damage); // TODO: unhardcode asphyxiation?
Да.

2024-11-26 18:21 UTC, doublechest0 commented on Content.Server/Stories/Garrote/GarroteSystem.cs
> +        return angleFromFace >= minAngleFromFace;
Очень запутано.

В игре есть направления, в которые спрайты поворачиваются. Возможно стоит использовать их.

2024-11-26 19:36 UTC, Shegare commented
![image](https://github.com/user-attachments/assets/85287535-85bb-41f2-aa0e-690fa0ad01f7)

2024-12-02 17:30 UTC, Shegare commented
Миллион раз в дебаге пробежался, но так и не отследил как игра меняет направления спрайтов, но даже если бы нашёл, то не факт что позволил бы уровень доступа взаимодействовать.
Так что я решил написать свой метод для определения направления
(Если отклонишь то я сойду с ума...)

2024-12-09 20:24 UTC, closed without merging