Draft: Energy cores
Space-Stories/space-station-14 pull request #57
Opened 2024-08-19 15:47 UTC by aristophanivan

Ядра Темного
Пишем-пишем-пишем ядра.
Функции: 
1) источник энергии
2) гравген
3) гироскоп
Приколы:
1) для работы требуется газ в зависимости от ядра
2) может сломаться
3) будет чиниться сваркой
4) крутые анимации)))

2024-08-20 10:21 UTC, doublechest0 commented
Перенеси текстуры в Stories папку

2024-08-22 18:16 UTC, doublechest0 requested changes
Использование ключей, которое есть сомнительно и лучше использовать доступы. Думаю, весь клиентский код можно заменить https://docs.spacestation14.com/en/ss14-by-example/making-a-sprite-dynamic.html.

Код системы это ужас, поэтому позже напишу, что нужно исправить.

2024-08-22 18:16 UTC, doublechest0 commented on Content.Shared/Power/EnergyCores/EnergyCoreComponent.cs
Разделить компонент по функционалу, если уместно.
Убрать клиентские EnablingLenght и тд. (Перенеся в клиентский EnergyCoreVisualsComponent, если не получится используя https://docs.spacestation14.com/en/ss14-by-example/making-a-sprite-dynamic.html , избавится от клиентского кода)

2024-08-22 18:16 UTC, doublechest0 commented on Content.Server/Gravity/GravityGeneratorComponent.cs
Вместо работы с компонентом, используй GravityGeneratorSystem, которая имеет к нему доступ.

2024-08-22 18:16 UTC, doublechest0 commented on Content.Server/Power/EnergyCores/EnergyCoreSystem.cs
> +            _nextTickCore += TimeSpan.FromSeconds(1);
Хардкод одной секунды

2024-08-22 18:16 UTC, doublechest0 commented on Content.Server/Power/EnergyCores/EnergyCoreSystem.cs
Это полный *******. Это настолько плохо написано, что, пожалуй, напишу об ошибках позже.

2024-08-22 18:16 UTC, doublechest0 commented on Content.Server/Power/EnergyCores/EnergyCoreKeyComponent.cs
Заменить ключи ядер на обычный доступ, как у ящиков или считывать доступ айди карты, которую вставят в ядро. (Айди карта может быть условным ключем с его текстуркой и названием)

2024-08-22 18:16 UTC, doublechest0 commented on space-stories
Зачем?

2024-08-23 05:58 UTC, aristophanivan commented on Content.Shared/Power/EnergyCores/EnergyCoreComponent.cs
А что с EnablingLenght не так? Типа эта фигня указывает на то, сколько длится анимация, чтоб ее вовремя переключить. Это учитывая то, что у каждого ядра разная длина анимации.

2024-08-23 06:00 UTC, aristophanivan commented on Content.Server/Gravity/GravityGeneratorComponent.cs
Смотри, там дело в том, что для работы GravityGenerator требует в системе везде того, что ядро будет запитано Apc проводами, а я замышлял то, чтоб даже без Apc проводов гравитация работала.

2024-08-23 06:01 UTC, aristophanivan commented on space-stories
Что зачем?

2024-08-23 06:05 UTC, aristophanivan commented on Content.Server/Power/EnergyCores/EnergyCoreKeyComponent.cs
Заказчик хотел ключи, ничего, как говорится, не знаю.

2024-08-23 06:08 UTC, aristophanivan commented on Resources/Textures/Stories/Structures/Machines/EnergyCores/key_of_sphere.rsi/meta.json
Ну это окей

2024-08-23 06:08 UTC, aristophanivan commented on Resources/Prototypes/Entities/Objects/Specific/EnergyCores/energycorekey.yml
Ок

2024-08-23 06:13 UTC, aristophanivan commented on Resources/Prototypes/dark_tags.yml
Ок

2024-08-23 06:27 UTC, aristophanivan commented on space-stories
А, это. Без понятия, что оно тут делает.
Ща удалю.

2024-08-25 02:00 UTC, doublechest0 commented on Content.Server/Power/EnergyCores/EnergyCoreKeyComponent.cs
Ключи могут использовать доступы под капотом, вместо написания такой непрактичной системы.

2024-08-25 02:00 UTC, doublechest0 commented on Content.Shared/Power/EnergyCores/EnergyCoreComponent.cs
Ошибся с EnablingLenght.

Перенеси логику нагрева и охлаждения газами в другой компонент.

2024-09-03 05:22 UTC, aristophanivan commented
Проект временно заморожен.

2024-10-10 16:48 UTC, aristophanivan commented
Отозвано.

2024-10-10 16:48 UTC, closed without merging