Обновление, ура
Space-Stories/space-station-14 pull request #70
Opened 2024-08-28 17:27 UTC by aristophanivan

## О PR
- Добавлены русские буквы-декали
- Добавлен промышленный глушитель синдиката. 

## Почему / Баланс
Опять же, просба doublechest

## Технические детали
Кода нет

**Changelog**
:cl:
- add: Добавлены русские буквы.
- add: Добавлен промышленный глушитель синдиката.

2024-08-28 18:12 UTC, doublechest0 requested changes

2024-08-28 18:12 UTC, doublechest0 commented on Resources/Prototypes/Corvax/Decals/crayons.yml
Перенести спрайты в Stories папку из Corvax. Перенести прототипы аналогично.

2024-08-28 18:12 UTC, doublechest0 commented on Resources/Prototypes/Stories/Catalog/uplink_catalog.yml
> +  - UplinkDisruption
```suggestion
- type: listing
  id: UplinkRadioJammerIndustrial
  name: Экспериментальный глушитель связи
  description: Это устройство является улучшенной версией обычного глушителя связи. Радиус действия увеличен, но и потребление больше.
  productEntity: RadioJammerIndustrial
  cost:
    Telecrystal: 6
  categories:
  - UplinkDisruption
```

За столько ТК никто это не купит.

2024-08-28 18:12 UTC, doublechest0 commented on Resources/Prototypes/Stories/Entities/Objects/Tools/jammer.yml
> +        startingItem: PowerCellHigh
```suggestion
- type: entity
  name: экспериментальный глушитель связи.
  parent: RadioJammer
  id: RadioJammerIndustrial
  description: Это устройство является улучшенной версией обычного глушителя связи. Радиус действия увеличен, но и потребление больше.
  components:
  - type: Sprite
    sprite: Stories/Objects/Devices/jammer_ind.rsi
  - type: RadioJammer
    settings:
    - wattage: 3
      range: 6
      message: radio-jammer-component-set-message-low
      name: radio-jammer-component-setting-low
    - wattage: 6
      range: 12
      message: radio-jammer-component-set-message-medium
      name: radio-jammer-component-setting-medium
    - wattage: 12
      range: 24
      message: radio-jammer-component-set-message-high
      name: radio-jammer-component-setting-high
  - type: ItemSlots
    slots:
      cell_slot:
        name: power-cell-slot-component-slot-name-default
        startingItem: PowerCellHigh
```

2024-08-28 18:12 UTC, doublechest0 commented on Resources/Textures/Stories/Objects/Devices/jammer_ind.rsi/meta.json
> +    "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/bfc9c6ba8126ee8c41564d68c4bfb9ce37faa8f8",
Ложь.

2024-08-28 18:26 UTC, aristophanivan commented on Resources/Prototypes/Stories/Catalog/uplink_catalog.yml
> +  - UplinkDisruption
Обычная 6 стоит, какой смысл?

2024-08-28 18:26 UTC, aristophanivan commented on Resources/Prototypes/Corvax/Decals/crayons.yml
Так они же корваксовские... Ладно...

2024-08-28 18:27 UTC, aristophanivan commented on Resources/Textures/Stories/Objects/Devices/jammer_ind.rsi/meta.json
> +    "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/bfc9c6ba8126ee8c41564d68c4bfb9ce37faa8f8",
Бывает, исправим)

2024-08-28 18:49 UTC, doublechest0 commented on Resources/Prototypes/Stories/Catalog/uplink_catalog.yml
> +  - UplinkDisruption
4 стоит обычная

2024-08-29 10:57 UTC, doublechest0 approved these changes

2024-08-29 10:59 UTC, merged