Reflectors
Space-Stories/space-station-14 pull request #76
Opened 2024-09-01 18:13 UTC by NikitosAseev

## О PR

Добавлены рефлекторы а именно "Коробка" , "Угловой" . "Двойной-Угловой"
Так же их изучение в РНД, крафт плат и самих рефлекторов

## Почему / Баланс

Позволит придумывать различные схемы по поддержанию сингулярности.
РНД может использовать для безопасного дальнего взаемодействия с аномалией
Потенциально будет нужен для СверМатерии 

## Технические детали

Whitelist / Blacklist - указывать какие типы проджектайлов мы хотим отражать

BlockedDirections - при попадании в эту сторону отражение не будет происходить ( блокируется грубо говоря )

ReflectionDirection - куда будет отражен снаряд, по умолчанию он null так как в случае углового отражения - указывать сторону не нужно

ReflectorType - Simple и Angular ( два типа отражения, одиночный и угловой, для одиночного нужно еще будет указать сторону отражения ReflectionDirection ) 

## Медиа

- [ ] Я добавил к этому PR скриншоты/видео, демонстрирующие его изменения в игре, **или** этот PR не требует демонстрации в игре

**Changelog**

<!--
Убедитесь, что вы убрали этот шаблон Changelog из блока комментариев, чтобы он отображался.
:cl:
- add: Добавлены рефлекторы!

2024-09-02 13:43 UTC, aristophanivan commented
Рефлекторы - круто. Освободившийся Дэн - еще лучше)

2024-09-14 13:12 UTC, doublechest0 requested changes

2024-09-14 13:12 UTC, doublechest0 commented on RobustToolbox
Убери.

2024-09-14 13:12 UTC, doublechest0 commented on runclient-Tools.sh
Убери.

2024-09-14 13:12 UTC, doublechest0 commented on runclient.sh
Убери.

2024-09-14 13:12 UTC, doublechest0 commented on runserver-Tools.sh
Убери.

2024-09-14 13:12 UTC, doublechest0 commented on runserver.sh
Убери.

2024-09-14 13:12 UTC, doublechest0 commented on Resources/Prototypes/Research/industrial.yml
> +  - ReflectorCornerTsideMachineCircuitboard
```suggestion
  - ReflectorBoxMachineCircuitboard # Stories
  - ReflectorCornerMachineCircuitboard # Stories
  - ReflectorCornerTsideMachineCircuitboard # Stories
```

2024-09-14 13:12 UTC, doublechest0 commented on Resources/Prototypes/Recipes/Lathes/electronics.yml
> +  result: ReflectorCornerTsideMachineCircuitboard
Перенеси в Stories папку.

2024-09-14 13:12 UTC, doublechest0 commented on Resources/Prototypes/Recipes/Lathes/electronics.yml
> -     Glass: 250
Не форматируй код оффов.

2024-09-15 07:00 UTC, NikitosAseev commented
@doublechest0 вроде все сделал

2024-09-15 11:38 UTC, doublechest0 commented
Сделай новую технологию, которая будет в Stories папках для них.

2024-09-21 10:55 UTC, doublechest0 requested changes

2024-09-21 10:55 UTC, doublechest0 commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ReflectorCornerTsideMachineCircuitboard # Stories
Ты добавил новую технологию, но тут не убрал.

2024-09-21 14:17 UTC, NikitosAseev commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ReflectorCornerTsideMachineCircuitboard # Stories
это dynamicRecipes , иначе говоря при изучении технологии отражения у принтера схем открывается рецепт
без него при изучении рецепта плат не будет

2024-09-22 10:21 UTC, doublechest0 commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ReflectorCornerTsideMachineCircuitboard # Stories
Понял.

2024-09-22 10:21 UTC, merged